name: odbootd

on: [push]

jobs:
  build-mac:
    name: Build odbootd (macOS)
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'pcercuei/libini'
        path: 'libini'
    - name: Configure, build and install libini
      run: |
        cmake -Bbuild
        cmake --build build --parallel
        sudo cmake --install build
      working-directory: libini
    - uses: actions/checkout@v2
      with:
        repository: 'pcercuei/libopk'
        path: 'libopk'
    - name: Configure, build and install libopk
      run: |
        cmake -Bbuild
        cmake --build build --target opk --parallel
        sudo cmake --install build
      working-directory: libopk
    - uses: actions/checkout@v2
      with:
        path: 'odbootd'
    - name: Install required packages
      run: brew install libusb
    - name: Configure, build and package odbootd
      run: |
        cmake -DWITH_ODBOOTD=OFF -Bbuild
        cmake --build build --parallel
      working-directory: odbootd
    - name: copy libraries
      run: |
        mkdir output
        cp libini/build/*.dylib output/
        cp libopk/build/*.dylib output/
        cp odbootd/build/odboot-client output/
        echo "If you have SIP activated and cannot run \`odboot-client\`, execute \`xattr -r -d com.apple.quarantine *\` on the folder with all the files" >> output/README.md
        install_name_tool -add_rpath @executable_path/. output/odboot-client
        cd output && tar -cvf odboot-client.tar *
    - uses: actions/upload-artifact@v2
      with:
        name: odbootd-macos
        path: |
          output/odboot-client.tar

